"""Build the inclusion manifest: SHA-256 of every tracked file.

The manifest excludes generated synthetic outputs (which are reproducible from
code) and the cooperative lock marker. It is built non-circularly: the
manifest file itself is excluded from its own hash list, then verified.

Usage:
    python3 shared/validation/build_manifest.py
"""
from __future__ import annotations

import hashlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MANIFEST = ROOT / "validation" / "INCLUDED_FILES_SHA256.md"

# Files that are reproducible synthetic outputs, not source-of-truth inputs.
# They are tracked separately in build receipts, not in the file manifest.
# `.locks/` holds cooperative per-task lock markers (e.g. a released
# `umg_zcp.lock`); like `STAGING_LOCK.md`, these are coordination artifacts,
# not tracked sources, so the whole directory is excluded.
EXCLUDE_DIRS = {
    ".git", "__pycache__", ".pytest_cache", ".mypy_cache", ".locks",
}
EXCLUDE_FILENAMES = {
    ".DS_Store", "STAGING_LOCK.md", "LICENSE_PENDING.md",
}
# The manifest itself is excluded from its own hash list (non-circular).
SELF_REL = "validation/INCLUDED_FILES_SHA256.md"


def _should_skip(path: Path) -> bool:
    parts = set(path.relative_to(ROOT).parts)
    if parts & EXCLUDE_DIRS:
        return True
    if path.name in EXCLUDE_FILENAMES:
        return True
    if path.suffix.lower() == ".log":
        return True
    # Skip generated synthetic data (reproducible from the generators).
    rel = path.relative_to(ROOT)
    if len(rel.parts) >= 3 and rel.parts[0] == "projects" and rel.parts[2] == "data":
        return True
    return False


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def build_manifest() -> dict:
    entries = []
    for path in sorted(ROOT.rglob("*")):
        if not path.is_file():
            continue
        if path.is_symlink():
            continue
        rel = path.relative_to(ROOT).as_posix()
        if rel == SELF_REL:
            continue
        if _should_skip(path):
            continue
        entries.append({
            "path": rel,
            "size": path.stat().st_size,
            "sha256": _sha256(path),
        })
    return {"entries": entries, "count": len(entries)}


def render(manifest: dict) -> str:
    lines = [
        "# INCLUDED_FILES_SHA256.md",
        "",
        "Deterministic SHA-256 manifest of every tracked source file in the",
        "portfolio repository. Generated by `shared/validation/build_manifest.py`.",
        "Excludes: generated synthetic data (reproducible), cooperative lock,",
        "Python caches, and this manifest file itself (non-circular).",
        "",
        f"Total tracked files: **{manifest['count']}**",
        "",
        "| Path | Size (bytes) | SHA-256 |",
        "|---|---:|---|",
    ]
    for e in manifest["entries"]:
        lines.append(f"| `{e['path']}` | {e['size']} | `{e['sha256']}` |")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    manifest = build_manifest()
    MANIFEST.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST.write_text(render(manifest), encoding="utf-8")
    # Non-circular verification: re-read and confirm every listed hash matches
    # the file on disk.
    mismatches = []
    for e in manifest["entries"]:
        p = ROOT / e["path"]
        if not p.exists() or _sha256(p) != e["sha256"]:
            mismatches.append(e["path"])
    if mismatches:
        print(f"FAIL: {len(mismatches)} manifest entries did not verify:",
              file=sys.stderr)
        for m in mismatches:
            print(f"  {m}", file=sys.stderr)
        return 1
    print(f"OK: {manifest['count']} tracked files verified.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
